/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-11-22 00:29:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.serotonin.mango.Common;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(18);
    _jspx_dependants.put("/WEB-INF/lib/seroUtils.jar", Long.valueOf(1626572386000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/ScadaBR/tomcat/webapps/ScadaBR/WEB-INF/lib/seroUtils.jar!/META-INF/serotonin.tld", Long.valueOf(1302093804000L));
    _jspx_dependants.put("/WEB-INF/tags/help.tag", Long.valueOf(1626572386000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/ScadaBR/tomcat/webapps/ScadaBR/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1274197894000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/ScadaBR/tomcat/webapps/ScadaBR/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1274197894000L));
    _jspx_dependants.put("/WEB-INF/tags/decl.tagf", Long.valueOf(1626572386000L));
    _jspx_dependants.put("/WEB-INF/tags/page.tag", Long.valueOf(1630868414000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc.jar", Long.valueOf(1626572382000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/ScadaBR/tomcat/webapps/ScadaBR/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1274197894000L));
    _jspx_dependants.put("/WEB-INF/tld/mango.tld", Long.valueOf(1626572382000L));
    _jspx_dependants.put("/WEB-INF/tags/menuItem.tag", Long.valueOf(1626572384000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1626572386000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/ScadaBR/tomcat/webapps/ScadaBR/WEB-INF/lib/spring-webmvc.jar!/META-INF/spring.tld", Long.valueOf(1192703364000L));
    _jspx_dependants.put("/WEB-INF/tags/img.tag", Long.valueOf(1626572386000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/tech.jsp", Long.valueOf(1626572384000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-log.jar", Long.valueOf(1626572384000L));
    _jspx_dependants.put("/WEB-INF/tags/alarmLevelOptions.tag", Long.valueOf(1626572386000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/ScadaBR/tomcat/webapps/ScadaBR/WEB-INF/lib/taglibs-log.jar!/META-INF/taglib.tld", Long.valueOf(1042464458000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.serotonin.mango.Common");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsst_005fi18n_0026_005fkey_005fescapeDQuotes_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsst_005fi18n_0026_005fkey_005fescapeDQuotes_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fsst_005fi18n_0026_005fkey_005fescapeDQuotes_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  tag:page
      org.apache.jsp.tag.web.page_tag _jspx_th_tag_005fpage_005f0 = new org.apache.jsp.tag.web.page_tag();
      _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fpage_005f0);
      try {
        _jspx_th_tag_005fpage_005f0.setJspContext(_jspx_page_context);
        // /WEB-INF/jsp/users.jsp(22,0) name = dwr type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
        _jspx_th_tag_005fpage_005f0.setDwr("UsersDwr");
        // /WEB-INF/jsp/users.jsp(22,0) name = onload type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
        _jspx_th_tag_005fpage_005f0.setOnload("init");
        _jspx_th_tag_005fpage_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_tag_005fpage_005f0, null));
        _jspx_th_tag_005fpage_005f0.doTag();
      } finally {
        _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fpage_005f0);
      }
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(52,101) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("userProfiles.none");
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f1_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(77,80) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f1.setKey("common.access.none");
      int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      _jspx_th_fmt_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f2_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(79,80) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f2.setKey("common.access.read");
      int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      _jspx_th_fmt_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f3_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f3.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(82,84) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f3.setKey("common.access.set");
      int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      _jspx_th_fmt_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f4_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f4.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(261,28) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f4.setKey("users.dataSaved");
      int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      _jspx_th_fmt_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f5_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f5.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(268,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f5.setKey("users.added");
      int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
      _jspx_th_fmt_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f6 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f6_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f6.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(273,33) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f6.setKey("users.saved");
      int _jspx_eval_fmt_005fmessage_005f6 = _jspx_th_fmt_005fmessage_005f6.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
      _jspx_th_fmt_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sst_005fi18n_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sst:i18n
    com.serotonin.web.taglib.LocalizableMessageTag _jspx_th_sst_005fi18n_005f0 = (com.serotonin.web.taglib.LocalizableMessageTag) _005fjspx_005ftagPool_005fsst_005fi18n_0026_005fkey_005fescapeDQuotes_005fnobody.get(com.serotonin.web.taglib.LocalizableMessageTag.class);
    boolean _jspx_th_sst_005fi18n_005f0_reused = false;
    try {
      _jspx_th_sst_005fi18n_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sst_005fi18n_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(338,21) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sst_005fi18n_005f0.setKey("users.deleteConfirm");
      // /WEB-INF/jsp/users.jsp(338,21) name = escapeDQuotes type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sst_005fi18n_005f0.setEscapeDQuotes(true);
      int _jspx_eval_sst_005fi18n_005f0 = _jspx_th_sst_005fi18n_005f0.doStartTag();
      if (_jspx_th_sst_005fi18n_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005fsst_005fi18n_0026_005fkey_005fescapeDQuotes_005fnobody.reuse(_jspx_th_sst_005fi18n_005f0);
      _jspx_th_sst_005fi18n_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sst_005fi18n_005f0, _jsp_getInstanceManager(), _jspx_th_sst_005fi18n_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f7 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f7_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f7.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(364,41) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f7.setKey("users.title");
      int _jspx_eval_fmt_005fmessage_005f7 = _jspx_th_fmt_005fmessage_005f7.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
      _jspx_th_fmt_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fhelp_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:help
    org.apache.jsp.tag.web.help_tag _jspx_th_tag_005fhelp_005f0 = new org.apache.jsp.tag.web.help_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fhelp_005f0);
    try {
      _jspx_th_tag_005fhelp_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fhelp_005f0.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(365,16) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fhelp_005f0.setId("userAdministration");
      _jspx_th_tag_005fhelp_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fhelp_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fimg_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:img
    org.apache.jsp.tag.web.img_tag _jspx_th_tag_005fimg_005f0 = new org.apache.jsp.tag.web.img_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fimg_005f0);
    try {
      _jspx_th_tag_005fimg_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fimg_005f0.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(367,32) name = png type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f0.setPng("user_add");
      // /WEB-INF/jsp/users.jsp(367,32) name = onclick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f0.setOnclick((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("showUser(${applicationScope['constants.Common.NEW_ID']}, false)", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/users.jsp(367,32) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f0.setTitle("users.add");
      // /WEB-INF/jsp/users.jsp(367,32) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f0.setId((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("u${applicationScope['constants.Common.NEW_ID']}Img", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      _jspx_th_tag_005fimg_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fimg_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fimg_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:img
    org.apache.jsp.tag.web.img_tag _jspx_th_tag_005fimg_005f1 = new org.apache.jsp.tag.web.img_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fimg_005f1);
    try {
      _jspx_th_tag_005fimg_005f1.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fimg_005f1.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(373,18) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f1.setId("u_TEMPLATE_Img");
      // /WEB-INF/jsp/users.jsp(373,18) name = png type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f1.setPng("user_green");
      // /WEB-INF/jsp/users.jsp(373,18) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f1.setTitle("users.user");
      _jspx_th_tag_005fimg_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fimg_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fimg_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:img
    org.apache.jsp.tag.web.img_tag _jspx_th_tag_005fimg_005f2 = new org.apache.jsp.tag.web.img_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fimg_005f2);
    try {
      _jspx_th_tag_005fimg_005f2.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fimg_005f2.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(385,41) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f2.setId("userImg");
      // /WEB-INF/jsp/users.jsp(385,41) name = png type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f2.setPng("user_green");
      // /WEB-INF/jsp/users.jsp(385,41) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f2.setTitle("users.user");
      _jspx_th_tag_005fimg_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fimg_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f8 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f8_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f8.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(386,16) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f8.setKey("users.details");
      int _jspx_eval_fmt_005fmessage_005f8 = _jspx_th_fmt_005fmessage_005f8.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
      _jspx_th_fmt_005fmessage_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f8, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fimg_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:img
    org.apache.jsp.tag.web.img_tag _jspx_th_tag_005fimg_005f3 = new org.apache.jsp.tag.web.img_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fimg_005f3);
    try {
      _jspx_th_tag_005fimg_005f3.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fimg_005f3.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(389,16) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f3.setId("saveImg");
      // /WEB-INF/jsp/users.jsp(389,16) name = png type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f3.setPng("save");
      // /WEB-INF/jsp/users.jsp(389,16) name = onclick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f3.setOnclick("saveUser();");
      // /WEB-INF/jsp/users.jsp(389,16) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f3.setTitle("common.save");
      _jspx_th_tag_005fimg_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fimg_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fimg_005f4(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:img
    org.apache.jsp.tag.web.img_tag _jspx_th_tag_005fimg_005f4 = new org.apache.jsp.tag.web.img_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fimg_005f4);
    try {
      _jspx_th_tag_005fimg_005f4.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fimg_005f4.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(390,16) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f4.setId("deleteImg");
      // /WEB-INF/jsp/users.jsp(390,16) name = png type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f4.setPng("delete");
      // /WEB-INF/jsp/users.jsp(390,16) name = onclick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f4.setOnclick("deleteUser();");
      // /WEB-INF/jsp/users.jsp(390,16) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f4.setTitle("common.delete");
      // /WEB-INF/jsp/users.jsp(390,16) name = style type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f4.setStyle("display:none;");
      _jspx_th_tag_005fimg_005f4.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fimg_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fimg_005f5(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:img
    org.apache.jsp.tag.web.img_tag _jspx_th_tag_005fimg_005f5 = new org.apache.jsp.tag.web.img_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fimg_005f5);
    try {
      _jspx_th_tag_005fimg_005f5.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fimg_005f5.setParent(_jspx_parent);
      // /WEB-INF/jsp/users.jsp(391,16) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f5.setId("sendTestEmailImg");
      // /WEB-INF/jsp/users.jsp(391,16) name = png type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f5.setPng("email_go");
      // /WEB-INF/jsp/users.jsp(391,16) name = onclick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f5.setOnclick("sendTestEmail();");
      // /WEB-INF/jsp/users.jsp(391,16) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f5.setTitle("common.sendTestEmail");
      // /WEB-INF/jsp/users.jsp(391,16) name = style type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_tag_005fimg_005f5.setStyle("display:none;");
      _jspx_th_tag_005fimg_005f5.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fimg_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f9(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f9 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f9_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f9.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f9.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(404,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f9.setKey("users.username");
      int _jspx_eval_fmt_005fmessage_005f9 = _jspx_th_fmt_005fmessage_005f9.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f9);
      _jspx_th_fmt_005fmessage_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f9, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f10(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f10 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f10_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f10.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f10.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(408,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f10.setKey("users.newPassword");
      int _jspx_eval_fmt_005fmessage_005f10 = _jspx_th_fmt_005fmessage_005f10.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f10);
      _jspx_th_fmt_005fmessage_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f10, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f11(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f11 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f11_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f11.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f11.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(412,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f11.setKey("users.email");
      int _jspx_eval_fmt_005fmessage_005f11 = _jspx_th_fmt_005fmessage_005f11.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f11);
      _jspx_th_fmt_005fmessage_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f11, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f12(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f12 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f12_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f12.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f12.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(416,36) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f12.setKey("users.phone");
      int _jspx_eval_fmt_005fmessage_005f12 = _jspx_th_fmt_005fmessage_005f12.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f12);
      _jspx_th_fmt_005fmessage_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f12, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f13(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f13 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f13_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f13.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f13.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(420,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f13.setKey("common.administrator");
      int _jspx_eval_fmt_005fmessage_005f13 = _jspx_th_fmt_005fmessage_005f13.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f13);
      _jspx_th_fmt_005fmessage_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f13, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f14(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f14 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f14_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f14.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f14.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(424,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f14.setKey("common.disabled");
      int _jspx_eval_fmt_005fmessage_005f14 = _jspx_th_fmt_005fmessage_005f14.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f14);
      _jspx_th_fmt_005fmessage_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f14, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f15(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f15 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f15_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f15.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f15.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(428,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f15.setKey("users.receiveAlarmEmails");
      int _jspx_eval_fmt_005fmessage_005f15 = _jspx_th_fmt_005fmessage_005f15.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f15);
      _jspx_th_fmt_005fmessage_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f15, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005falarmLevelOptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:alarmLevelOptions
    org.apache.jsp.tag.web.alarmLevelOptions_tag _jspx_th_tag_005falarmLevelOptions_005f0 = new org.apache.jsp.tag.web.alarmLevelOptions_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005falarmLevelOptions_005f0);
    try {
      _jspx_th_tag_005falarmLevelOptions_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005falarmLevelOptions_005f0.setParent(_jspx_parent);
      _jspx_th_tag_005falarmLevelOptions_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005falarmLevelOptions_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f16(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f16 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f16_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f16.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f16.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(432,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f16.setKey("users.receiveOwnAuditEvents");
      int _jspx_eval_fmt_005fmessage_005f16 = _jspx_th_fmt_005fmessage_005f16.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f16);
      _jspx_th_fmt_005fmessage_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f16, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f17(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f17 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f17_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f17.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f17.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(437,36) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f17.setKey("userProfiles.selectName");
      int _jspx_eval_fmt_005fmessage_005f17 = _jspx_th_fmt_005fmessage_005f17.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f17);
      _jspx_th_fmt_005fmessage_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f17, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f17_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f18(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f18 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f18_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f18.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f18.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/users.jsp(446,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f18.setKey("users.dataSources");
      int _jspx_eval_fmt_005fmessage_005f18 = _jspx_th_fmt_005fmessage_005f18.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f18);
      _jspx_th_fmt_005fmessage_005f18_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f18, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f18_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public void invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    var userId = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("    var editingUserId;\r\n");
      out.write("    var dataSources;\r\n");
      out.write("    var adminUser;\r\n");
      out.write("    \r\n");
      out.write("    function init() {\r\n");
      out.write("    	\r\n");
      out.write("    	UsersDwr.getInitData(function(data) {\r\n");
      out.write("            if (data.admin) {\r\n");
      out.write("            	show(\"usersProfilesListTable\");\r\n");
      out.write("                adminUser = true;\r\n");
      out.write("            \r\n");
      out.write("            	\r\n");
      out.write("                show(\"userList\");\r\n");
      out.write("                show(\"usernameRow\");\r\n");
      out.write("                show(\"administrationRow\");\r\n");
      out.write("                show(\"disabledRow\");\r\n");
      out.write("                show(\"deleteImg\");\r\n");
      out.write("                show(\"sendTestEmailImg\");\r\n");
      out.write("                \r\n");
      out.write("            	\r\n");
      out.write("                var i, j;\r\n");
      out.write("                for (i=0; i<data.users.length; i++) {\r\n");
      out.write("                    appendUser(data.users[i].id);\r\n");
      out.write("                    updateUser(data.users[i]);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var usersProfileHtml = \"\", userProfileId, userProfileName;\r\n");
      out.write("                usersProfileHtml += \"<option value=\" + ");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      boolean _jspx_th_c_005fout_005f0_reused = false;
      try {
        _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fout_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
        // /WEB-INF/jsp/users.jsp(52,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fout_005f0.setValue( Common.NEW_ID );
        int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
        if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
        _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
        _jspx_th_c_005fout_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
      }
      out.write(" + \">\"+ \"");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("\" + \"</option>\";\r\n");
      out.write("                \r\n");
      out.write("                for (k=0; k<data.usersProfiles.length; k++) {\r\n");
      out.write("                	userProfileId = data.usersProfiles[k].id;\r\n");
      out.write("                	userProfileName = data.usersProfiles[k].name;\r\n");
      out.write("                	usersProfileHtml += \"<option value=\" + userProfileId + \">\"+ userProfileName + \"</option>\";\r\n");
      out.write("                }\r\n");
      out.write("                $(\"usersProfilesList\").innerHTML = usersProfileHtml;\r\n");
      out.write("                \r\n");
      out.write("            	\r\n");
      out.write("                var dshtml = \"\", id, dp;\r\n");
      out.write("                dataSources = data.dataSources;\r\n");
      out.write("                for (i=0; i<dataSources.length; i++) {\r\n");
      out.write("                    id = \"ds\"+ dataSources[i].id;\r\n");
      out.write("                    dshtml += '<input type=\"checkbox\" id=\"'+ id +'\" onclick=\"dataSourceChange(this)\">';\r\n");
      out.write("                    dshtml += '<label for=\"'+ id +'\"> '+ dataSources[i].name +'</label><br/>';\r\n");
      out.write("                    dshtml += '<div style=\"margin-left:25px;\" id=\"dsps'+ dataSources[i].id +'\">';\r\n");
      out.write("                    if (dataSources[i].points.length > 0) {\r\n");
      out.write("                        dshtml +=   '<table cellspacing=\"0\" cellpadding=\"1\">';\r\n");
      out.write("                        for (j=0; j<dataSources[i].points.length; j++) {\r\n");
      out.write("                            dp = dataSources[i].points[j];\r\n");
      out.write("                            dshtml += '<tr>';\r\n");
      out.write("                            dshtml +=   '<td class=\"formLabelRequired\">'+ dp.name +'</td>';\r\n");
      out.write("                            dshtml +=   '<td>';\r\n");
      out.write("                            dshtml +=     '<input type=\"radio\" name=\"dp'+ dp.id +'\" id=\"dp'+ dp.id +'/0\" value=\"0\">';\r\n");
      out.write("                            dshtml +=             '<label for=\"dp'+ dp.id +'/0\">");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_parent, _jspx_page_context))
        return;
      out.write("</label> ';\r\n");
      out.write("                            dshtml +=     '<input type=\"radio\" name=\"dp'+ dp.id +'\" id=\"dp'+ dp.id +'/1\" value=\"1\">';\r\n");
      out.write("                            dshtml +=             '<label for=\"dp'+ dp.id +'/1\">");
      if (_jspx_meth_fmt_005fmessage_005f2(_jspx_parent, _jspx_page_context))
        return;
      out.write("</label> ';\r\n");
      out.write("                            if (dp.settable) {\r\n");
      out.write("                                dshtml +=     '<input type=\"radio\" name=\"dp'+ dp.id +'\" id=\"dp'+ dp.id +'/2\" value=\"2\">';\r\n");
      out.write("                                dshtml +=             '<label for=\"dp'+ dp.id +'/2\">");
      if (_jspx_meth_fmt_005fmessage_005f3(_jspx_parent, _jspx_page_context))
        return;
      out.write("</label>';\r\n");
      out.write("                            }\r\n");
      out.write("                            dshtml +=   '</td>';\r\n");
      out.write("                            dshtml += '</tr>';\r\n");
      out.write("                        }\r\n");
      out.write("                        dshtml +=   '</table>';\r\n");
      out.write("                    }\r\n");
      out.write("                    dshtml += '</div>';\r\n");
      out.write("                }\r\n");
      out.write("                $(\"dataSourceList\").innerHTML = dshtml;\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("            	\r\n");
      out.write("                // Not an admin user.\r\n");
      out.write("                adminUser = false;\r\n");
      out.write("                editingUserId = data.user.id;\r\n");
      out.write("                showUserCB(data.user);\r\n");
      out.write("                hide(\"usersProfilesListTable\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function showUser(userId, hideMsg) {\r\n");
      out.write("    	\r\n");
      out.write("    	if (hideMsg)\r\n");
      out.write("            setUserMessage();\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("        if (editingUserId)\r\n");
      out.write("            stopImageFader($(\"u\"+ editingUserId +\"Img\"));\r\n");
      out.write("        editingUserId = userId;\r\n");
      out.write("        UsersDwr.getUser(userId, showUserCB);\r\n");
      out.write("        startImageFader($(\"u\"+ editingUserId +\"Img\"));\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function showUserCB(user) {\r\n");
      out.write("    	\r\n");
      out.write("        show($(\"userDetails\"));\r\n");
      out.write("        $set(\"username\", user.username);\r\n");
      out.write("        $set(\"password\", user.password);\r\n");
      out.write("        $set(\"email\", user.email);\r\n");
      out.write("        $set(\"phone\", user.phone);\r\n");
      out.write("        $set(\"administrator\", user.admin);\r\n");
      out.write("        $set(\"disabled\", user.disabled);\r\n");
      out.write("        $set(\"receiveAlarmEmails\", user.receiveAlarmEmails);\r\n");
      out.write("        $set(\"receiveOwnAuditEvents\", user.receiveOwnAuditEvents);\r\n");
      out.write("\r\n");
      out.write("    	\r\n");
      out.write("        if(user.id != ");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      boolean _jspx_th_c_005fout_005f1_reused = false;
      try {
        _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fout_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
        // /WEB-INF/jsp/users.jsp(131,22) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fout_005f1.setValue( Common.NEW_ID );
        int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
        if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
        _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
        _jspx_th_c_005fout_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
      }
      out.write(") {\r\n");
      out.write("        	 $set(\"usersProfilesList\", user.userProfile);\r\n");
      out.write("        	 show(\"deleteImg\");\r\n");
      out.write("        	 //console.log(\"User profile: \" + user.userProfile);\r\n");
      out.write("        } else {\r\n");
      out.write("			 hide(\"deleteImg\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    	\r\n");
      out.write("        if (adminUser) {\r\n");
      out.write("            // Turn off all data sources and set all data points to 'none'.\r\n");
      out.write("            var i, j, dscb, dp;\r\n");
      out.write("            for (i=0; i<dataSources.length; i++) {\r\n");
      out.write("                dscb = $(\"ds\"+ dataSources[i].id);\r\n");
      out.write("                dscb.checked = false;\r\n");
      out.write("                dataSourceChange(dscb);\r\n");
      out.write("                for (j=0; j<dataSources[i].points.length; j++)\r\n");
      out.write("                    $set(\"dp\"+ dataSources[i].points[j].id, \"0\");\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Turn on the data sources to which the user has permission.\r\n");
      out.write("            for (i=0; i<user.dataSourcePermissions.length; i++) {\r\n");
      out.write("                dscb = $(\"ds\"+ user.dataSourcePermissions[i]);\r\n");
      out.write("                dscb.checked = true;\r\n");
      out.write("                dataSourceChange(dscb);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Update the data point permissions.\r\n");
      out.write("            for (i=0; i<user.dataPointPermissions.length; i++)\r\n");
      out.write("                $set(\"dp\"+ user.dataPointPermissions[i].dataPointId, user.dataPointPermissions[i].permission);\r\n");
      out.write("            stopImageFader($(\"u\"+ user.id +\"Img\"));\r\n");
      out.write("        	\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //setUserMessage();\r\n");
      out.write("    	\r\n");
      out.write("        updateUserImg();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function setDataSourcesNone() {\r\n");
      out.write("        var i;\r\n");
      out.write("        for (i=0; i<dataSources.length; i++) {\r\n");
      out.write("            dscb = $(\"ds\"+ dataSources[i].id);\r\n");
      out.write("            dscb.checked = false;\r\n");
      out.write("            dataSourceChange(dscb);\r\n");
      out.write("            for (j=0; j<dataSources[i].points.length; j++)\r\n");
      out.write("                $set(\"dp\"+ dataSources[i].points[j].id, \"0\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function hideDataSources() {\r\n");
      out.write("    	hide(\"dataSources\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function showDataSources() {\r\n");
      out.write("    	show(\"dataSources\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function checkProfile(){\r\n");
      out.write("    	var profile = document.getElementById(\"usersProfilesList\");\r\n");
      out.write("    	if(profile.options[profile.selectedIndex].value > 0){\r\n");
      out.write("    		hideDataSources();  \r\n");
      out.write("    	} else {\r\n");
      out.write("    		//setDataSourcesNone();\r\n");
      out.write("    		showDataSources();\r\n");
      out.write("    	}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function saveUser() {\r\n");
      out.write(" 		\r\n");
      out.write("		startImageFader($(\"saveImg\"));\r\n");
      out.write("    	\r\n");
      out.write("		// Prevent illegal characters in username\r\n");
      out.write("		if ($get(\"username\").includes(\"<\") || $get(\"username\").includes(\">\")) {\r\n");
      out.write("			alert(\"Error: illegal characters in username: > or <\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// Prevent forbidden word \"new\" in usernames/passwords/emails\r\n");
      out.write("		if ($get(\"username\").match(/\\bnew .*/) || $get(\"password\").match(/\\bnew .*/) || $get(\"email\").match(/\\bnew .*/)) {\r\n");
      out.write("			alert(\"Error: you cannot use the word 'new' in these fields!\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		setUserMessage();\r\n");
      out.write("        if (adminUser) {\r\n");
      out.write("    		startImageFader($(\"u\"+ editingUserId +\"Img\"));\r\n");
      out.write("           // Create the list of allowed data sources and data point permissions.\r\n");
      out.write("            var i, j;\r\n");
      out.write("            var dsPermis = new Array();\r\n");
      out.write("            var dpPermis = new Array();\r\n");
      out.write("            var dpval;\r\n");
      out.write("            \r\n");
      out.write("            // If a profile is select, reset other permissions on DSs.\r\n");
      out.write("            if($get(\"usersProfileList\") == ");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      boolean _jspx_th_c_005fout_005f2_reused = false;
      try {
        _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fout_005f2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
        // /WEB-INF/jsp/users.jsp(225,43) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fout_005f2.setValue( Common.NEW_ID );
        int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
        if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
        _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
        _jspx_th_c_005fout_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
      }
      out.write(")\r\n");
      out.write("            {\r\n");
      out.write("        		setDataSourcesNone();\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            for (i=0; i<dataSources.length; i++) {\r\n");
      out.write("                if ($(\"ds\"+ dataSources[i].id).checked)\r\n");
      out.write("                    dsPermis[dsPermis.length] = dataSources[i].id;\r\n");
      out.write("                else {\r\n");
      out.write("                    for (j=0; j<dataSources[i].points.length; j++) {\r\n");
      out.write("                        dpval = $get(\"dp\"+ dataSources[i].points[j].id);\r\n");
      out.write("                        if (dpval == \"1\" || dpval == \"2\")\r\n");
      out.write("                            dpPermis[dpPermis.length] = {dataPointId: dataSources[i].points[j].id, permission: dpval};\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            UsersDwr.saveUserAdmin(editingUserId, $get(\"username\"), $get(\"password\"), $get(\"email\"), $get(\"phone\"), \r\n");
      out.write("                    $get(\"administrator\"), $get(\"disabled\"), $get(\"receiveAlarmEmails\"), $get(\"receiveOwnAuditEvents\"),\r\n");
      out.write("                    dsPermis, dpPermis, $get(\"usersProfilesList\"), saveUserCB);\r\n");
      out.write("        }\r\n");
      out.write("        else\r\n");
      out.write("            UsersDwr.saveUser(editingUserId, $get(\"password\"), $get(\"email\"), $get(\"phone\"),\r\n");
      out.write("                    $get(\"receiveAlarmEmails\"), $get(\"receiveOwnAuditEvents\"), $get(\"usersProfilesList\"), saveUserCB);\r\n");
      out.write("     \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function saveUserCB(response) {\r\n");
      out.write("    	show(\"deleteImg\");\r\n");
      out.write("        stopImageFader($(\"saveImg\"));\r\n");
      out.write("        if (response.hasMessages) {\r\n");
      out.write("            showDwrMessages(response.messages, \"genericMessages\");\r\n");
      out.write("            hide(\"deleteImg\");\r\n");
      out.write("        }\r\n");
      out.write("        else if (!adminUser)\r\n");
      out.write("            setUserMessage(\"");
      if (_jspx_meth_fmt_005fmessage_005f4(_jspx_parent, _jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("        else {\r\n");
      out.write("            if (editingUserId == ");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      boolean _jspx_th_c_005fout_005f3_reused = false;
      try {
        _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
        _jspx_th_c_005fout_005f3.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
        // /WEB-INF/jsp/users.jsp(263,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fout_005f3.setValue( Common.NEW_ID );
        int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
        if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new javax.servlet.jsp.SkipPageException();
        }
        _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
        _jspx_th_c_005fout_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
      }
      out.write(") {\r\n");
      out.write("                stopImageFader($(\"u\"+ editingUserId +\"Img\"));\r\n");
      out.write("                editingUserId = response.data.userId;\r\n");
      out.write("                appendUser(editingUserId);\r\n");
      out.write("                startImageFader($(\"u\"+ editingUserId +\"Img\"));\r\n");
      out.write("                setUserMessage(\"");
      if (_jspx_meth_fmt_005fmessage_005f5(_jspx_parent, _jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("                UsersDwr.getUser(editingUserId, updateUser);\r\n");
      out.write("	            showUser(editingUserId, false);\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("	                setUserMessage(\"");
      if (_jspx_meth_fmt_005fmessage_005f6(_jspx_parent, _jspx_page_context))
        return;
      out.write("\");\r\n");
      out.write("		            UsersDwr.getUser(editingUserId, updateUser);\r\n");
      out.write("		            showUser(editingUserId, false);\r\n");
      out.write("                }\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function sendTestEmail() {\r\n");
      out.write("        UsersDwr.sendTestEmail($get(\"email\"), $get(\"username\"), function(result) {\r\n");
      out.write("            stopImageFader($(\"sendTestEmailImg\"));\r\n");
      out.write("            if (result.exception)\r\n");
      out.write("                setUserMessage(result.exception);\r\n");
      out.write("            else\r\n");
      out.write("                setUserMessage(result.message);\r\n");
      out.write("        });\r\n");
      out.write("        startImageFader($(\"sendTestEmailImg\"));\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function setUserMessage(message) {\r\n");
      out.write("        if (message){\r\n");
      out.write("            $set(\"userMessage\", message);\r\n");
      out.write("        //console.log(\"show message - \" + message);\r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("            $set(\"userMessage\");\r\n");
      out.write("            //console.log(\"hide messages\");\r\n");
      out.write("            hideContextualMessages(\"userDetails\");\r\n");
      out.write("            hideGenericMessages(\"genericMessages\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function appendUser(userId) {\r\n");
      out.write("        createFromTemplate(\"u_TEMPLATE_\", userId, \"usersTable\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function updateUser(user) {\r\n");
      out.write("        $(\"u\"+ user.id +\"Username\").innerHTML = user.username;\r\n");
      out.write("        setUserImg(user.admin, user.disabled, $(\"u\"+ user.id +\"Img\"));\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function updateUserImg() {\r\n");
      out.write("    	\r\n");
      out.write("        var admin = $get(\"administrator\");\r\n");
      out.write("        if (adminUser) {\r\n");
      out.write("            if (admin) {\r\n");
      out.write("                	$(\"usersProfilesList\").disabled = true;\r\n");
      out.write("                	\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("	                $(\"usersProfilesList\").disabled = false;\r\n");
      out.write("	            	\r\n");
      out.write("            }\r\n");
      out.write("            checkProfile();	\r\n");
      out.write("        	\r\n");
      out.write("        }\r\n");
      out.write("        setUserImg(admin, $get(\"disabled\"), $(\"userImg\"));\r\n");
      out.write("    	\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function dataSourceChange(dscb) {\r\n");
      out.write("        display(\"dsps\"+ dscb.id.substring(2), !dscb.checked);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function deleteUser() {\r\n");
      out.write("        if (confirm(\"");
      if (_jspx_meth_sst_005fi18n_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("\")) {\r\n");
      out.write("        	var userId = editingUserId;\r\n");
      out.write("            startImageFader(\"deleteImg\");\r\n");
      out.write("            UsersDwr.deleteUser(userId, function(response) {\r\n");
      out.write("                stopImageFader(\"deleteImg\");\r\n");
      out.write("                \r\n");
      out.write("                if (response.hasMessages)\r\n");
      out.write("                	setUserMessage(response.messages[0].genericMessage);\r\n");
      out.write("                else {\r\n");
      out.write("                    stopImageFader(\"u\"+ userId +\"Img\");\r\n");
      out.write("                    $(\"usersTable\").removeChild($(\"u\"+ userId));\r\n");
      out.write("                    hide(\"userDetails\");\r\n");
      out.write("                    editingUserId = null;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <table>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td valign=\"top\" id=\"userList\" style=\"display:none;\">\r\n");
      out.write("        <div class=\"borderDiv\">\r\n");
      out.write("          <table width=\"100%\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>\r\n");
      out.write("                <span class=\"smallTitle\">");
      if (_jspx_meth_fmt_005fmessage_005f7(_jspx_parent, _jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("                ");
      if (_jspx_meth_tag_005fhelp_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("              <td align=\"right\">");
      if (_jspx_meth_tag_005fimg_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <table id=\"usersTable\">\r\n");
      out.write("            <tbody id=\"u_TEMPLATE_\" onclick=\"showUser(getMangoId(this), true)\" class=\"ptr\" style=\"display:none;\"><tr>\r\n");
      out.write("              <td>");
      if (_jspx_meth_tag_005fimg_005f1(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"link\" id=\"u_TEMPLATE_Username\"></td>\r\n");
      out.write("            </tr></tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </td>\r\n");
      out.write("      \r\n");
      out.write("      <td valign=\"top\" style=\"display:none;\" id=\"userDetails\">\r\n");
      out.write("        <div class=\"borderDiv\">\r\n");
      out.write("          <table width=\"100%\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>\r\n");
      out.write("                <span class=\"smallTitle\">");
      if (_jspx_meth_tag_005fimg_005f2(_jspx_parent, _jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_fmt_005fmessage_005f8(_jspx_parent, _jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td align=\"right\">\r\n");
      out.write("                ");
      if (_jspx_meth_tag_005fimg_005f3(_jspx_parent, _jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_tag_005fimg_005f4(_jspx_parent, _jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_tag_005fimg_005f5(_jspx_parent, _jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          \r\n");
      out.write("          <table><tbody id=\"genericMessages\"></tbody></table>\r\n");
      out.write("          \r\n");
      out.write("          <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td colspan=\"2\" id=\"userMessage\" class=\"formError\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr id=\"usernameRow\" style=\"display:none;\">\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f9(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"username\" type=\"text\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f10(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"password\" type=\"text\" maxlength=\"20\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f11(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"email\" type=\"text\" class=\"formLong\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"formLabel\">");
      if (_jspx_meth_fmt_005fmessage_005f12(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"phone\" type=\"text\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr id=\"administrationRow\" style=\"display:none;\">\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f13(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"administrator\" type=\"checkbox\" onclick=\"updateUserImg();\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr id=\"disabledRow\" style=\"display:none;\">\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f14(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"disabled\" type=\"checkbox\" onclick=\"updateUserImg();\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f15(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><select id=\"receiveAlarmEmails\">");
      if (_jspx_meth_tag_005falarmLevelOptions_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("</select></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f16(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><input id=\"receiveOwnAuditEvents\" type=\"checkbox\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tbody id=\"usersProfilesListTable\" style=\"display:none;\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td class=\"formLabel\">");
      if (_jspx_meth_fmt_005fmessage_005f17(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("              <td class=\"formField\"><select id=\"usersProfilesList\" onchange=\"checkProfile()\">\r\n");
      out.write("              </select></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <tbody id=\"dataSources\" style=\"display:none;\">\r\n");
      out.write("              <tr><td class=\"horzSeparator\" colspan=\"2\"></td></tr>\r\n");
      out.write("              <tr id=\"dataSources\">\r\n");
      out.write("                <td class=\"formLabelRequired\">");
      if (_jspx_meth_fmt_005fmessage_005f18(_jspx_parent, _jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("                <td class=\"formField\" id=\"dataSourceList\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      return;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
